sudo: false

language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  - TOX_ENV=py3
  - TOX_ENV=docs
  - TOX_ENV=flake8

install:
  - "pip3 install tox"

script:
  - "tox -e $TOX_ENV"

notifications:
  email: false
